[package]
name = "chip-8"
version = "0.1.0"
authors = ["Casey White <cwhite2019@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
